import type { Localized } from "./types";

// Shared interface copy (section eyebrows/titles, buttons, form, nav).
export const ui = {
  hero: {
    exploreCta: { en: "Explore ecosystem", vi: "Khám phá hệ sinh thái" } as Localized,
    vrCta: { en: "VR Tour", vi: "Tham quan VR" } as Localized,
    scroll: { en: "Scroll", vi: "Cuộn" } as Localized,
  },
  showcase: {
    eyebrow: { en: "Featured", vi: "Tiêu biểu" } as Localized,
    title: { en: "Showcase", vi: "Sản phẩm nổi bật" } as Localized,
    lead: {
      en: "Hardware and immersive builds where students learn by making — and by debugging what they make.",
      vi: "Những sản phẩm phần cứng và trải nghiệm nhập vai, nơi học sinh học bằng cách tạo ra — và gỡ lỗi chính thứ mình tạo ra.",
    } as Localized,
    watchDemo: { en: "Watch demo", vi: "Xem demo" } as Localized,
  },
  spotlight: {
    eyebrow: { en: "Interactive", vi: "Tương tác" } as Localized,
    title: { en: "Meet PTalk", vi: "Gặp gỡ PTalk" } as Localized,
    lead: {
      en: "Everything we build is meant to be touched, moved, and explored. Here's PTalk, live in 3D — drag to spin it, scroll to zoom in.",
      vi: "Mọi thứ chúng tôi tạo ra đều để chạm, di chuyển và khám phá. Đây là PTalk, sống động trong không gian 3D — kéo để xoay, cuộn để phóng to.",
    } as Localized,
    hint: { en: "Drag to rotate · scroll to zoom", vi: "Kéo để xoay · cuộn để phóng to" } as Localized,
    steps: [
      {
        title: { en: "Voice-native", vi: "Trò chuyện giọng nói" } as Localized,
        desc: { en: "Natural spoken dialogue", vi: "Đối thoại tự nhiên bằng giọng nói" } as Localized,
      },
      {
        title: { en: "Realtime", vi: "Thời gian thực" } as Localized,
        desc: { en: "Instant, low-latency responses", vi: "Phản hồi tức thì, độ trễ thấp" } as Localized,
      },
      {
        title: { en: "Built for learning", vi: "Học tập" } as Localized,
        desc: { en: "A companion for STEM classrooms", vi: "Trợ lý đồng hành cho lớp học STEM" } as Localized,
      },
    ],
  },
  ecosystem: {
    eyebrow: { en: "Ecosystem", vi: "Hệ sinh thái" } as Localized,
    title: { en: "App highlights", vi: "Ứng dụng tiêu biểu" } as Localized,
    ssoPrefix: { en: "All apps connected via ", vi: "Tất cả ứng dụng kết nối qua " } as Localized,
    ssoStrong: { en: "Single Sign-On", vi: "Đăng nhập một lần" } as Localized,
    learnMore: { en: "Learn more", vi: "Tìm hiểu thêm" } as Localized,
  },
  team: {
    eyebrow: { en: "The people", vi: "Con người" } as Localized,
    title: { en: "The team", vi: "Đội ngũ" } as Localized,
    lead: {
      en: "Mentors and makers from PTIT building the lab, one project at a time.",
      vi: "Những người cố vấn và sáng tạo từ PTIT cùng xây dựng phòng lab, qua từng dự án.",
    } as Localized,
  },
  partners: {
    eyebrow: { en: "Collaboration", vi: "Hợp tác" } as Localized,
    title: { en: "Partners & collaborations", vi: "Đối tác & Hợp tác" } as Localized,
  },
  contact: {
    eyebrow: { en: "Reach out", vi: "Kết nối" } as Localized,
    title: { en: "Contact", vi: "Liên hệ" } as Localized,
    heading: { en: "Get in touch", vi: "Liên hệ với chúng tôi" } as Localized,
    blurb: {
      en: "Interested in our research, products, or collaboration opportunities? We'd love to hear from you.",
      vi: "Quan tâm đến nghiên cứu, sản phẩm hay cơ hội hợp tác của chúng tôi? Chúng tôi rất mong được lắng nghe bạn.",
    } as Localized,
    emailLabel: { en: "Email", vi: "Email" } as Localized,
    phoneLabel: { en: "Phone", vi: "Điện thoại" } as Localized,
    addressLabel: { en: "Address", vi: "Địa chỉ" } as Localized,
    nameLabel: { en: "Name", vi: "Họ tên" } as Localized,
    namePlaceholder: { en: "Your name", vi: "Tên của bạn" } as Localized,
    emailPlaceholder: { en: "your@email.com", vi: "ban@email.com" } as Localized,
    messageLabel: { en: "Message", vi: "Lời nhắn" } as Localized,
    messagePlaceholder: { en: "Tell us about your inquiry…", vi: "Hãy cho chúng tôi biết bạn cần gì…" } as Localized,
    send: { en: "Send message", vi: "Gửi lời nhắn" } as Localized,
    sending: { en: "Sending…", vi: "Đang gửi…" } as Localized,
    success: { en: "Message sent — thank you!", vi: "Đã gửi — cảm ơn bạn!" } as Localized,
    error: { en: "Something went wrong. Please try again.", vi: "Đã có lỗi xảy ra. Vui lòng thử lại." } as Localized,
  },
  auth: {
    signIn: { en: "Sign in", vi: "Đăng nhập" } as Localized,
    signUp: { en: "Sign up", vi: "Đăng ký" } as Localized,
    signOut: { en: "Sign out", vi: "Đăng xuất" } as Localized,
    account: { en: "Account", vi: "Tài khoản" } as Localized,
    members: { en: "Members", vi: "Thành viên" } as Localized,
    admin: { en: "Admin", vi: "Quản trị" } as Localized,
    profile: { en: "Profile", vi: "Hồ sơ" } as Localized,
    memberLead: {
      en: "Your gateway to the CTS ecosystem — one account across every app.",
      vi: "Cổng vào hệ sinh thái CTS — một tài khoản cho mọi ứng dụng.",
    } as Localized,
    adminStub: {
      en: "Management tools are coming — game review and user management land here.",
      vi: "Công cụ quản trị sắp có — duyệt game và quản lý người dùng sẽ ở đây.",
    } as Localized,
  },
  nav: {
    download: { en: "Download", vi: "Tải xuống" } as Localized,
    viewAll: { en: "View all products", vi: "Xem tất cả sản phẩm" } as Localized,
    getInTouch: { en: "Get in touch", vi: "Liên hệ" } as Localized,
    menu: { en: "Menu", vi: "Menu" } as Localized,
    backToTop: { en: "Back to top", vi: "Lên đầu trang" } as Localized,
  },
  footer: {
    contact: { en: "Contact", vi: "Liên hệ" } as Localized,
    follow: { en: "Follow us", vi: "Theo dõi" } as Localized,
    rights: { en: "All rights reserved.", vi: "Bảo lưu mọi quyền." } as Localized,
    privacy: { en: "Privacy Policy", vi: "Chính sách bảo mật" } as Localized,
    terms: { en: "Terms of Use", vi: "Điều khoản sử dụng" } as Localized,
  },
  products: {
    eyebrow: { en: "Our apps", vi: "Ứng dụng của chúng tôi" } as Localized,
    title: { en: "Products", vi: "Sản phẩm" } as Localized,
    intro: {
      en: "Explore our unified ecosystem of applications. Sign in once with your CTS account and reach every app seamlessly.",
      vi: "Khám phá hệ sinh thái ứng dụng hợp nhất của chúng tôi. Đăng nhập một lần bằng tài khoản CTS và truy cập mọi ứng dụng liền mạch.",
    } as Localized,
    downloadHeading: { en: "Download our apps", vi: "Tải ứng dụng của chúng tôi" } as Localized,
    download: { en: "Download", vi: "Tải xuống" } as Localized,
    backText: { en: "Interested in our research and other projects?", vi: "Quan tâm đến nghiên cứu và các dự án khác của chúng tôi?" } as Localized,
    backCta: { en: "Explore our full ecosystem", vi: "Khám phá toàn bộ hệ sinh thái" } as Localized,
  },
  device: {
    title: { en: "Order the physical device", vi: "Đặt thiết bị vật lý" } as Localized,
    blurb: {
      en: "Want the hardware for your school or home? Contact the lab to order a device or arrange a trial.",
      vi: "Muốn có thiết bị cho trường hoặc gia đình? Liên hệ lab để đặt thiết bị hoặc sắp xếp dùng thử.",
    } as Localized,
    cta: { en: "Contact to order", vi: "Liên hệ đặt thiết bị" } as Localized,
    subjectPrefix: { en: "Device order:", vi: "Đặt thiết bị:" } as Localized,
  },
  vrTour: {
    eyebrow: { en: "PTIT Virtual Tour", vi: "Tham quan ảo PTIT" } as Localized,
    loading: { en: "Loading the 360° campus experience…", vi: "Đang tải trải nghiệm khuôn viên 360°…" } as Localized,
    back: { en: "Back", vi: "Quay lại" } as Localized,
    backHome: { en: "Back", vi: "Quay lại" } as Localized,
    backToCampus: { en: "Main campus", vi: "Khuôn viên chính" } as Localized,
    entryTitle: { en: "360° experience", vi: "Trải nghiệm 360°" } as Localized,
    entryLead: { en: "Tour the PTIT campus in virtual reality.", vi: "Tham quan khuôn viên PTIT bằng thực tế ảo." } as Localized,
    enter: { en: "Start", vi: "Bắt đầu" } as Localized,
    statusCampus: { en: "PTIT CAMPUS · 360°", vi: "KHUÔN VIÊN PTIT · 360°" } as Localized,
    statusCie: { en: "CIE CENTER · 360°", vi: "TRUNG TÂM CIE · 360°" } as Localized,
  },
  home: {
    heroEyebrow: { en: "Learn · Create · Play ecosystem", vi: "Hệ sinh thái Học · Sáng tạo · Chơi" } as Localized,
    heroLead: { en: "Where", vi: "Nơi công nghệ" } as Localized,
    heroKw1: { en: "AI,", vi: "AI," } as Localized, // brand red
    heroKw2: { en: "STEM & VR", vi: "STEM & VR" } as Localized, // brand red
    heroTail: { en: "converge under one roof.", vi: "hội tụ trong một mái nhà." } as Localized,
    featured: { en: "Featured", vi: "Nổi bật" } as Localized,
    vrCardLabel: { en: "164 scenes · 360°", vi: "164 cảnh · 360°" } as Localized,
    vrCardTitle: { en: "Tour the PTIT campus", vi: "Tham quan campus PTIT" } as Localized,
    vrCardBlurb: {
      en: "Walk through lecture halls, labs and the library in VR — right in your browser.",
      vi: "Đi xuyên giảng đường, phòng lab và thư viện bằng VR ngay trên trình duyệt.",
    } as Localized,
    gamehubName: { en: "CTS Gamehub", vi: "CTS Gamehub" } as Localized,
    gamehubBlurb: {
      en: "Browse and play the lab's games — rolling out soon.",
      vi: "Duyệt và chơi game của lab — sắp ra mắt.",
    } as Localized,
    statUsers: { en: "Users", vi: "Người dùng" } as Localized,
    statDownloads: { en: "Downloads", vi: "Lượt tải" } as Localized,
    statSchools: { en: "Schools & classes", vi: "Trường / lớp học" } as Localized,
    statApps: { en: "AI products", vi: "Sản phẩm AI" } as Localized,
    statScenes: { en: "360° VR scenes", vi: "Cảnh VR 360°" } as Localized,
    statTeam: { en: "Team members", vi: "Thành viên" } as Localized,
    statPartner: { en: "Academic partner", vi: "Đối tác học thuật" } as Localized,
    ctaEyebrow: { en: "Collaborate", vi: "Hợp tác" } as Localized,
    ctaButton: { en: "Email us", vi: "Gửi email cho chúng tôi" } as Localized,
    comingSoon: { en: "Coming soon", vi: "Sắp ra mắt" } as Localized,
    underConstruction: {
      en: "This section is being rebuilt — check back soon.",
      vi: "Mục này đang được hoàn thiện — quay lại sau nhé.",
    } as Localized,
  },
  whatWeDo: {
    eyebrow: { en: "What we build", vi: "Chúng tôi làm gì" } as Localized,
    title: { en: "Four ways we make learning physical", vi: "Bốn cách biến bài học thành điều chạm được" } as Localized,
    lead: {
      en: "Robots, immersive worlds, AI tools, and games — built so students learn by doing.",
      vi: "Robot, thế giới nhập vai, công cụ AI và games — tạo ra để học sinh học bằng cách làm.",
    } as Localized,
    pillars: [
      { key: "robot", title: { en: "Robots", vi: "Robot" } as Localized, desc: { en: "Hands-on STEM hardware", vi: "Phần cứng STEM thực hành" } as Localized },
      { key: "vr", title: { en: "VR worlds", vi: "Thế giới VR" } as Localized, desc: { en: "360° campus & labs", vi: "Khuôn viên & phòng lab 360°" } as Localized },
      { key: "ai", title: { en: "AI tools", vi: "Công cụ AI" } as Localized, desc: { en: "Voice & learning companions", vi: "Trợ lý giọng nói & học tập" } as Localized },
      { key: "games", title: { en: "Games", vi: "Games" } as Localized, desc: { en: "Play-to-learn experiences", vi: "Học qua trò chơi" } as Localized },
    ],
  },
  games: {
    hubTitle: { en: "Game Hub", vi: "Khu Game" } as Localized,
    hubLead: {
      en: "Play games built by the lab — right in your browser.",
      vi: "Chơi các game do lab tạo ra — ngay trên trình duyệt.",
    } as Localized,
    by: { en: "by", vi: "bởi" } as Localized,
    fullscreen: { en: "Fullscreen", vi: "Toàn màn hình" } as Localized,
    breadcrumb: { en: "Games", vi: "Games" } as Localized,
    heavyNote: {
      en: "Heavy game — best on desktop; first load may take a moment.",
      vi: "Game khá nặng — nên chơi trên máy tính; lần tải đầu có thể hơi lâu.",
    } as Localized,
    backToHub: { en: "Back to Game Hub", vi: "Quay lại Game Hub" } as Localized,
    fullscreenHint: { en: "Tap the ⛶ button to play fullscreen.", vi: "Bấm nút ⛶ để chơi toàn màn hình." } as Localized,
    about: { en: "About", vi: "Giới thiệu" } as Localized,
    info: { en: "Details", vi: "Thông tin" } as Localized,
    creator: { en: "Creator", vi: "Tác giả" } as Localized,
    genre: { en: "Genre", vi: "Thể loại" } as Localized,
    classification: { en: "Type", vi: "Phân loại" } as Localized,
    releaseStatus: { en: "Status", vi: "Trạng thái" } as Localized,
    links: { en: "Links", vi: "Liên kết" } as Localized,
    play: { en: "Play now", vi: "Chơi ngay" } as Localized,
    openLink: { en: "Open link", vi: "Mở liên kết" } as Localized,
    watchVideo: { en: "Watch video", vi: "Xem video" } as Localized,
    noDescription: { en: "No description yet.", vi: "Chưa có mô tả." } as Localized,
    comingSoonComments: { en: "Comments — coming soon", vi: "Bình luận — sắp ra mắt" } as Localized,
    searchPlaceholder: { en: "Search games…", vi: "Tìm game…" } as Localized,
    allFilter: { en: "All", vi: "Tất cả" } as Localized,
    filterClassification: { en: "Type", vi: "Phân loại" } as Localized,
    filterGenre: { en: "Genre", vi: "Thể loại" } as Localized,
    filterTag: { en: "Tag", vi: "Thẻ" } as Localized,
    gamesCount: { en: "{n} games", vi: "{n} game" } as Localized,
    noResults: { en: "No games match your filters", vi: "Không có game khớp bộ lọc" } as Localized,
    clearFilters: { en: "Clear filters", vi: "Xoá bộ lọc" } as Localized,
  },
  gamesTeaser: {
    eyebrow: { en: "Play", vi: "Chơi" } as Localized,
    title: { en: "The lab's games hub", vi: "Khu game của lab" } as Localized,
    lead: {
      en: "Browse and play the games we build — rolling out soon.",
      vi: "Duyệt và chơi những game lab tạo ra — sắp ra mắt.",
    } as Localized,
    cta: { en: "Open Games", vi: "Vào khu Games" } as Localized,
  },
  ptalkChat: {
    intro: { en: "Ask PTalk", vi: "Hỏi thử PTalk" } as Localized,
    placeholder: { en: "Type a question…", vi: "Nhập câu hỏi…" } as Localized,
    send: { en: "Send", vi: "Gửi" } as Localized,
    emptyHint: {
      en: "Ask about learning, CTS products, or anything PTalk knows.",
      vi: "Hỏi về học tập, sản phẩm CTS, hay bất cứ điều gì PTalk biết.",
    } as Localized,
    signInPrompt: {
      en: "Sign in to try chatting with PTalk.",
      vi: "Đăng nhập để chat thử với PTalk.",
    } as Localized,
    signInCta: { en: "Sign in", vi: "Đăng nhập" } as Localized,
    quota: { en: "{n} tries left today", vi: "Còn {n} lượt hôm nay" } as Localized,
    limitReached: {
      en: "You've used all your tries today. Come back tomorrow!",
      vi: "Bạn đã dùng hết lượt thử hôm nay. Quay lại vào ngày mai nhé!",
    } as Localized,
    error: { en: "PTalk is busy — please try again.", vi: "PTalk đang bận, thử lại sau giây lát." } as Localized,
    privacyNote: {
      en: "This demo chat isn't saved.",
      vi: "Đoạn chat thử này không được lưu lại.",
    } as Localized,
    thinking: { en: "PTalk is thinking…", vi: "PTalk đang trả lời…" } as Localized,
  },
};
